#!/usr/bin/env bash
# Remove files generated by compile/run/test (logs, bytecode, temp captures).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

removed=0

remove_path() {
  local path=$1
  if [[ -e "$path" || -L "$path" ]]; then
    rm -rf -- "$path"
    echo "removed: $path"
    removed=$((removed + 1))
  fi
}

# Repo-root / CWD logs produced by samples and ad-hoc runs.
while IFS= read -r -d '' path; do
  remove_path "$path"
done < <(find . -maxdepth 1 -type f -name '*.log' -print0 2>/dev/null)

# Temp captures from CI smoke / GoogleTest helpers.
remove_path /tmp/branch_count.out
remove_path /tmp/munx_test_stderr.txt
remove_path "${TMPDIR:-/tmp}/munx_test_stderr.txt"
remove_path "${TMPDIR:-/tmp}/branch_count.out"

# Bytecode emitted next to sources during compile/--run.
while IFS= read -r -d '' path; do
  remove_path "$path"
done < <(find sample tests -type f -name '*.mxb' -print0 2>/dev/null || true)

# CTest / GoogleTest scratch under the build tree (keep binaries).
if [[ -d build ]]; then
  while IFS= read -r -d '' path; do
    remove_path "$path"
  done < <(find build -type f \( -name '*.log' -o -name 'LastTest.log' -o -name 'LastTestsFailed.log' \) -print0 2>/dev/null || true)
fi

echo "cleanup complete ($removed path(s) removed)"
